version: "3"

services:

  db:
    image: postgres:9.4
    restart: always
    tty: true
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bank
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8181:80"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:172.17.0.1"